#!/usr/bin/env bash
set -euo pipefail

PNG="bld/png/tube-holder-assembly.png"
STL="bld/stl/tube-holder-assembly.stl"
OUT="vrf/out"

for file in "$PNG" "$STL"; do
  if [[ ! -s "$file" ]]; then
    echo "ERROR: expected non-empty build output is missing: $file" >&2
    exit 1
  fi
done

TOOL_REF="$(awk '$1 == "ref:" { print $2; exit }' project.yml)"
if [[ -z "$TOOL_REF" ]]; then
  echo "ERROR: unable to resolve tool.scad-project ref from project.yml" >&2
  exit 1
fi

TOOL_SHA="$(git -C tools/tool.scad-project rev-parse HEAD)"
if [[ ! "$TOOL_SHA" =~ ^[0-9a-f]{40}$ ]]; then
  echo "ERROR: unable to resolve exact tool.scad-project gitlink commit" >&2
  exit 1
fi

RESOLVED_REF_SHA="$(git -C tools/tool.scad-project rev-parse "${TOOL_REF}^{commit}" 2>/dev/null || true)"
if [[ "$RESOLVED_REF_SHA" != "$TOOL_SHA" ]]; then
  echo "ERROR: tooling ref ${TOOL_REF} resolves to ${RESOLVED_REF_SHA:-<missing>} instead of gitlink ${TOOL_SHA}" >&2
  exit 1
fi

for mapping in \
  "build.yml:project-build" \
  "verify.yml:project-verify" \
  "release.yml:project-release"; do
  caller="${mapping%%:*}"
  reusable="${mapping#*:}"
  expected="brainboxemb/tool.scad-project/.github/workflows/${reusable}.yml@${TOOL_SHA}"
  if ! grep -Fq "$expected" ".github/workflows/${caller}"; then
    echo "ERROR: .github/workflows/${caller} is not pinned to exact tooling commit ${TOOL_SHA}" >&2
    exit 1
  fi
done

for script in bootstrap.ps1 bootstrap.sh update-repo.ps1 update-repo.sh; do
  canonical="tools/tool.scad-project/bootstrap/${script}"
  if ! cmp -s "$script" "$canonical"; then
    echo "ERROR: ${script} differs from canonical ${canonical}" >&2
    exit 1
  fi
done

mkdir -p "$OUT/png"
cp "$PNG" "$OUT/png/tube-holder-assembly.png"

cat > "$OUT/README.md" <<'EOF'
# Verification

This snapshot is generated by the template project's functional verification.

The verification checks that:

- the configured reference assembly produces both a non-empty PNG render and a non-empty STL export;
- the semantic `tool.scad-project` ref in `project.yml` resolves to the checked-out tool gitlink commit;
- Build, Verify and Release callers are pinned to that exact 40-character tool commit SHA;
- the root bootstrap/update scripts match the canonical copies from the pinned tool release.

## Render evidence

![Tube holder assembly](png/tube-holder-assembly.png)

The exact source commit and runtime/tooling versions are recorded separately in
`publication-info.txt` by `tool.scad-project`.
EOF

echo "Template functional verification: OK"
