#!/usr/bin/env bash
set -euo pipefail

PNG="bld/png/tube-holder-assembly.png"
STL="bld/stl/tube-holder-assembly.stl"
OUT="vrf/out"

for file in "$PNG" "$STL"; do
  if [[ ! -s "$file" ]]; then
    echo "ERROR: expected non-empty build output is missing: $file" >&2
    exit 1
  fi
done

mkdir -p "$OUT/png"
cp "$PNG" "$OUT/png/tube-holder-assembly.png"

cat > "$OUT/README.md" <<'EOF'
# Verification

This snapshot is generated by the template project's functional verification.

The verification checks that the configured reference assembly produces both a
non-empty PNG render and a non-empty STL export.

## Render evidence

![Tube holder assembly](png/tube-holder-assembly.png)

The exact source commit and runtime/tooling versions are recorded separately in
`publication-info.txt` by `tool.scad-project`.
EOF

echo "Template functional verification: OK"
