name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!release-request/**"
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: brainboxemb/tool.scad-project/.github/workflows/project-build.yml@v0.9.0
    with:
      artifact_name: template-scad-project-build
