name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: brainboxemb/tool.scad-project/.github/workflows/project-build.yml@40694891d3239401cb0ba4bfb35a3812d6584ab7
    with:
      artifact_name: template-scad-project-build
