name: PR cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    uses: brainboxemb/tool.git-project/.github/workflows/reusable-pr-preview-cleanup.yml@v0.2.9
    with:
      pr_number: ${{ github.event.pull_request.number }}
      preview_suffixes: |
        bld
        vrf
      delete_source_branch: true
