name: PR cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-pr-cleanup.yml@40694891d3239401cb0ba4bfb35a3812d6584ab7
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_branch_prefix: dev/pr
      delete_source_branch: true
