name: PR cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-pr-cleanup.yml@ba93e9165f8c23df3f867c2ae7fa160187166d9d
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_branch_prefix: dev/pr
      delete_source_branch: true
