name: SCAD production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  scad:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-production.yml@f8fa469c720535a0d091064d151b5abdadc3d6ed
    with:
      aggregate_task: consumer:scad.ci
      cache_namespace: template-scad-production-m004-step3-v1
