name: SCAD production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  scad:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-production.yml@5712324ea9e3a7c81ba1b79013f2758f52b219cf
    with:
      cache_namespace: template-scad-production-v2
