name: SCAD production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  scad:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-production.yml@2c974674c0d52875518a4320204f7005b3c9c421
    with:
      aggregate_task: consumer:scad.ci
      cache_namespace: template-scad-production-m004-step3-v1
