name: Verify

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!release-request/**"
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  verify:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: brainboxemb/tool.scad-project/.github/workflows/project-verify.yml@360b6aa950288adfad845fffccd0ffa41becd45c
    with:
      artifact_name: template-scad-project-verification
      verification_path: vrf/out
