name: Verify

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  verify:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: brainboxemb/tool.scad-project/.github/workflows/project-verify.yml@12c924eb4d0ef8f348c0947a2607f0a214d220da
    with:
      artifact_name: template-scad-project-verification
      verification_path: vrf/out
